AWSTemplateFormatVersion: "2010-09-09"

Description: "Launch everything except IAM users for one-click deployment."

Parameters:
  InternalS3BucketURI:
    Type: String
    Default: bytes-by-ying-postgres-as-app

  RDSMasterUsername:
    Type: String
    Default: someuser

  RDSMasterPassword:
    Type: String
    Default: somepassword

  RDSMasterDatabase:
    Type: String
    Default: somedb

  EC2KeyPair:
    Type: String
    Default: admin

  CustomDatabaseUsername:
    Type: String
    Default: myuser

  CustomDatabasePassword:
    Type: String
    Default: mypassword

  CustomDatabaseDatabase:
    Type: String
    Default: mydb

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${InternalS3BucketURI}/vpc.template"

  RDSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${InternalS3BucketURI}/rds.template"
      Parameters:
        DatabaseUsername: !Ref RDSMasterUsername
        DatabasePassword: !Ref RDSMasterPassword
        PostgresDBName: !Ref RDSMasterDatabase

  CustomDatabasePersistStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${InternalS3BucketURI}/persist.template"

  CustomDatabaseComputeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - CustomDatabasePersistStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${InternalS3BucketURI}/compute.template"
      Parameters:
        EC2KeyPair: !Ref EC2KeyPair
        EnvVarPostgresUser: !Ref CustomDatabaseUsername
        EnvVarPostgresPassword: !Ref CustomDatabasePassword
        EnvVarPostgresDatabase: !Ref CustomDatabaseDatabase
