AWSTemplateFormatVersion: "2010-09-09"

Description: "Launch everything except IAM users for one-click deployment."

Parameters:
  InternalS3BucketURI:
    Type: String
    Default: bytes-by-ying-postgres-as-app

  RDSMasterUsername:
    Type: String
    Default: root

  RDSMasterPassword:
    Type: String
    Default: root1234

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${InternalS3BucketURI}/vpc.template"

  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${InternalS3BucketURI}/rds.template"
      Parameters:
        DatabaseUsername: !Ref RDSMasterUsername
        DatabasePassword: !Ref RDSMasterPassword
