AWSTemplateFormatVersion: "2010-09-09"

Description: Data layer for custom database.

Resources:
  ApplicationBlockStore:
    Type: "AWS::EC2::Volume"
    Properties:
      AvailabilityZone: !Select
        - 0
        - "Fn::GetAZs": ""
      Size: 1
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-ebs"
      VolumeType: gp2
